[[actions]]
name = "check_large_file"
description = "Check for large files in commit"
command = "{BEAUTY_TIPS} builtin check-large-files -- --size=50k -- {{files...}}"

[[actions]]
name = "check_cargo_fmt"
description = "Run cargo fmt in check mode"
command = "cargo fmt --check -p {{cargo_targets}} -- --color=never"
inputs.files = [ "**/*.rs", "**/Cargo.toml" ]

[[actions]]
name = "fix_cargo_fmt"
description = "Run cargo fmt in fix mode"
command = "cargo fmt --all -p {{cargo_targets}} -- --color=never"
inputs.files = [ "**/*.rs", "**/Cargo.toml" ]
