[[actions]]
name = "check_large_file"
description = "Check for large files in commit"
command = "{BEAUTY_TIPS} builtin large-files -- --size=50k -- {{files...}}"

[[actions]]
name = "check_bom"
description = "Check files for a byte order mark"
command = "{BEAUTY_TIPS} builtin bom -- -- {{files...}}"

[[actions]]
name = "fix_bom"
description = "Remove byte-order-mark from files"
# --fix=(on|off): Turn fixing on or off
command = "{BEAUTY_TIPS} builtin bom -- --fix=on -- {{files...}}"

[[actions]]
name = "check_mixed_line_endings"
description = "Check files for mixed line endings"
command = "{BEAUTY_TIPS} builtin mixed-line-endings -- -- {{files...}}"

[[actions]]
name = "fix_mixed_line_endings"
description = "Unify files to consistently use one line ending"
# --fix=(cr|crlf|lf|auto): Fix towards one of the options or pick the
#         one used most widely in a file
command = "{BEAUTY_TIPS} builtin bom -- --fix=auto -- {{files...}}"

[[actions]]
name = "check_cargo_fmt"
description = "Run cargo fmt in check mode"
command = "cargo fmt --check -p {{cargo_targets}} -- --color=never"
inputs.files = [ "**/*.rs", "**/Cargo.toml" ]

[[actions]]
name = "fix_cargo_fmt"
description = "Run cargo fmt in fix mode"
command = "cargo fmt --all -p {{cargo_targets}} -- --color=never"
inputs.files = [ "**/*.rs", "**/Cargo.toml" ]
