[[actions]]
name = "github/check_actions"
description = "Run actionlint on github actions"
run-sequentially = false
command = "actionlint {{files...}}"
inputs.files = [".github/**/*.yaml", ".github/**/*.yml"]
