[[actions]]
name = "check_toml"
description = "Run taplo lint"
run-sequentially = false
command = "taplo lint --colors=never {{files...}}"

[[actions]]
name = "check_toml_fmt"
description = "Run taplo fmt"
run-sequentially = false
command = "cspell fmt --colors=never --check {{files...}}"

[[actions]]
name = "fix_toml_fmt"
description = "Run taplo fmt and have it fix the files"
run-sequentially = true
command = "cspell fmt --colors=never {{files...}}"
